package com.example.mymhealthmonitor;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;import org.json.*;

public class MainActivity extends Activity {
 SharedPreferences sp; LinearLayout cards; final String KEY="records"; SimpleDateFormat df=new SimpleDateFormat("dd MMM yyyy, hh:mm a",Locale.getDefault());
 int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(Color.rgb(23,32,42));return t;}
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);sp=getSharedPreferences("health",0);cards=findViewById(R.id.cards); refresh(); findViewById(R.id.addBtn).setOnClickListener(v->addDialog());findViewById(R.id.historyBtn).setOnClickListener(v->history());findViewById(R.id.profileBtn).setOnClickListener(v->profile());findViewById(R.id.reminderBtn).setOnClickListener(v->reminder());findViewById(R.id.rpmBtn).setOnClickListener(v->rpm());}
 GradientDrawable bg(){GradientDrawable g=new GradientDrawable();g.setColor(Color.WHITE);g.setCornerRadius(dp(16));return g;}
 void refresh(){cards.removeAllViews(); JSONObject x=last();String[] names={"🩺 Blood Pressure","❤️ Pulse","🫁 SpO₂","🌡️ Temperature","⚖️ Weight"};String[] keys={"bp","pulse","spo2","temp","weight"};String[] units={"mmHg","bpm","%","°C","kg"};for(int i=0;i<names.length;i++){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(12),dp(16),dp(12));c.setBackground(bg());TextView a=tv(names[i],16);a.setTypeface(null,1);TextView val=tv("No reading yet",22);try{if(x!=null&&x.has(keys[i]))val.setText(x.optString(keys[i])+" "+units[i]);}catch(Exception e){}c.addView(a);c.addView(val);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(6),0,dp(6));cards.addView(c,p);}}
 JSONObject last(){try{JSONArray a=new JSONArray(sp.getString(KEY,"[]"));return a.length()>0?a.getJSONObject(a.length()-1):null;}catch(Exception e){return null;}}
 JSONArray all(){try{return new JSONArray(sp.getString(KEY,"[]"));}catch(Exception e){return new JSONArray();}}
 void addDialog(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(20),dp(4),dp(20),0);String[] hint={"Systolic BP (mmHg)","Diastolic BP (mmHg)","Pulse (bpm)","SpO₂ (%)","Temperature (°C)","Weight (kg)"};EditText[] e=new EditText[6];for(int i=0;i<6;i++){e[i]=new EditText(this);e[i].setHint(hint[i]);e[i].setInputType(2|8192);l.addView(e[i]);}new AlertDialog.Builder(this).setTitle("Add health measurement").setView(l).setPositiveButton("Save",(d,w)->{try{JSONObject o=new JSONObject();o.put("time",df.format(new Date()));String[] k={"sys","dia","pulse","spo2","temp","weight"};for(int i=0;i<6;i++)if(e[i].getText().length()>0)o.put(k[i],e[i].getText().toString());if(o.length()>1){JSONArray a=all();a.put(o);sp.edit().putString(KEY,a.toString()).apply();refresh();}}catch(Exception z){}}).setNegativeButton("Cancel",null).show();}
 void history(){JSONArray a=all();LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(18),dp(6),dp(18),dp(6));TextView chart=tv("Blood pressure trend\n",16);l.addView(chart);for(int i=Math.max(0,a.length()-10);i<a.length();i++){JSONObject o=a.optJSONObject(i);String s=o.optString("time");if(o.has("sys"))s+="\nBP: "+o.optString("sys")+"/"+o.optString("dia");if(o.has("pulse"))s+="   Pulse: "+o.optString("pulse");if(o.has("spo2"))s+="   SpO₂: "+o.optString("spo2");TextView t=tv(s,14);t.setPadding(0,dp(8),0,dp(8));l.addView(t);}new AlertDialog.Builder(this).setTitle("History & trends").setView(l).setPositiveButton("Close",null).show();}
 void profile(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(20),0,dp(20),0);EditText n=new EditText(this);n.setHint("Name");EditText age=new EditText(this);age.setHint("Age");EditText h=new EditText(this);h.setHint("Height (cm)");EditText w=new EditText(this);w.setHint("Weight (kg)");l.addView(n);l.addView(age);l.addView(h);l.addView(w);n.setText(sp.getString("name",""));h.setText(sp.getString("height",""));w.setText(sp.getString("profileweight",""));new AlertDialog.Builder(this).setTitle("Profile & BMI").setView(l).setPositiveButton("Save",(d,x)->{sp.edit().putString("name",n.getText().toString()).putString("height",h.getText().toString()).putString("profileweight",w.getText().toString()).apply();try{double bmi=Double.parseDouble(w.getText().toString())/Math.pow(Double.parseDouble(h.getText().toString())/100,2);Toast.makeText(this,String.format(Locale.getDefault(),"BMI %.1f",bmi),Toast.LENGTH_LONG).show();}catch(Exception z){}}).setNegativeButton("Cancel",null).show();}
 void reminder(){TimePickerDialog d=new TimePickerDialog(this,(v,hh,mm)->{sp.edit().putInt("rh",hh).putInt("rm",mm).apply();Toast.makeText(this,String.format(Locale.getDefault(),"Reminder saved for %02d:%02d. Enable a recurring alarm in your phone if desired.",hh,mm),Toast.LENGTH_LONG).show();},sp.getInt("rh",9),sp.getInt("rm",0),true);d.setTitle("Daily measurement reminder");d.show();}
 void rpm(){new AlertDialog.Builder(this).setTitle("📡 RPM Teaching Demo").setMessage("PATIENT\n↓\nBP / SpO₂ / Pulse / Wearable\n↓\nMobile mHealth App\n↓\nInternet / Cloud\n↓\nRPM Dashboard\n↓\nHealthcare Professional\n↓\nTeleconsultation\n↓\nLaboratory investigation + LIS\n↓\nValidated digital report\n\nThis is a classroom workflow demonstration; it does not connect to a real hospital or cloud service in V1.").setPositiveButton("OK",null).show();}
}
